---

name: 1.1.5.runtime
group: Corosync
labels: generic
description: |
  Corosync is running with `token_retransmits_before_loss_const` set to `{{ expected['1.1.5'] }}`
remediation: |
  ## Abstract
  The runtime value of the corosync `token_retransmits_before_loss_const` parameter is not set as recommended

  ## Remediation
  Adjust the corosync `token_retransmits_before_loss_const` parameter as recommended on the Azure best practices, and reload the corosync service.

  ## References
  - https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker
implementation: "{{ lookup('file', 'roles/checks/'+name+'/tasks/main.yml') }}"

# check id. This value must not be changed over the life of this check
id: 15F7A8
