---

name: 1.1.5
group: Corosync
labels: generic
description: |
  Corosync `token_retransmits_before_loss_const` is set to: `{{ expected[name] }}`
remediation: |
  ## Remediation
  Adjust the corosync `token_retransmits_before_loss_const` parameter to `{{ expected[name] }}` as recommended by the Azure best practices.

  ## References
  - https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker
implementation: "{{ lookup('file', 'roles/checks/'+name+'/tasks/main.yml') }}"

# Test data
key_name: token_retransmits_before_loss_const

# check id. This value must not be changed over the life of this check
id: 21FCA6
