#!/bin/sh
if which nosetests-3.6 1>/dev/null 2>&1; then
	testexec="nosetests-3.6"
else
	testexec="nosetests"
fi

case `pwd` in
	*/test/unittests)
		PYTHONPATH=../.. $testexec -w . "$@"
		;;
	*/test)
		PYTHONPATH=.. $testexec -w unittests "$@"
		;;
	*)
		PYTHONPATH=. $testexec -w test/unittests "$@"
		;;
esac

