#!/bin/sh
case `pwd` in
	*/test/unittests)
		PYTHONPATH=../.. nosetests -w . "$@"
		;;
	*/test)
		PYTHONPATH=.. nosetests -w unittests "$@"
		;;
	*)
		PYTHONPATH=. nosetests -w test/unittests "$@"
		;;
esac

