Releasing crmsh version 3.0.1
=============================
:Author: Kristoffer Gronlund
:Email: kgronlund@suse.com
:Date: 2017-07-21 11:00

Hello everyone!

I'm happy to announce the release of crmsh version 3.0.1 today. This
is mainly a bug fix release, so no new exciting features and mainly
fixes to the new bootstrap functionality added in 3.0.0.

I would also like to take the opportinity to introduce a new core
developer for crmsh, Xin Liang! For this release he has contributed
some of the bug fixes discovered, but he has also contributed a
rewrite of hb_report into Python, as well as worked on improving the
tab completion support in crmsh. I also want to recognize the hard
work of Shiwen Zhang who initially started the work of rewriting the
hb_report script in Python.

For the complete list of changes in this release, see the ChangeLog:

* https://github.com/ClusterLabs/crmsh/blob/3.0.1/ChangeLog

The source code can be downloaded from Github:

* https://github.com/ClusterLabs/crmsh/releases/tag/3.0.1

This version of crmsh (or a version very close to it) is already
available in openSUSE Tumbleweed, and packages for several popular
Linux distributions will be available from the Stable repository at
the OBS:

* http://download.opensuse.org/repositories/network:/ha-clustering:/Stable/

Archives of the tagged release:

* https://github.com/ClusterLabs/crmsh/archive/3.0.1.tar.gz
* https://github.com/ClusterLabs/crmsh/archive/3.0.1.zip

As usual, a huge thank you to all contributors and users of crmsh!

Cheers,
Kristoffer
