#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

root="$(git rev-parse --show-toplevel)"
[ -d "$root" ] || exit 1

./update-data-manifest.sh
git add ./data-manifest
