---

- name: "{{ name }}.check"
  shell: |
    sbdarray=$(grep -E '^SBD_DEVICE=' /etc/sysconfig/sbd  | grep -oP 'SBD_DEVICE=\K[^.]+' | sed 's/\"//g')
    IFS=';' sbdarray=( $sbdarray )
    # convoluted, but normal count method does not work with jinja2
    # issue: https://github.com/ansible/ansible/issues/16968
    temp_ar=(${!sbdarray[@]});  device_count=`expr ${temp_ar[-1]} + 1`
    echo "$device_count"
  check_mode: false
  register: config_updated
  changed_when: config_updated.stdout != expected[name]

- block:
    - name: Post results
      import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is not changed }}"
