coverage:
  status:
    project:
      default:
        threshold: 0.1%
    patch:
      default:
        threshold: 0.1%
codecov: 
  notify:
    after_n_builds: 25
comment:
  after_n_builds: 25
  layout: "condensed_header, flags, files, condensed_footer"
