coverage:
  status:
    project:
      default:
        threshold: 0.35%
    patch:
      default:
        threshold: 0.35%
codecov: 
  notify:
    after_n_builds: 29
comment:
  after_n_builds: 29
  layout: "condensed_header, flags, files, condensed_footer"

ignore:
  - "crmsh/report"
