coverage:
  status:
    project:
      default:
        threshold: 0.35%
    patch:
      default:
        threshold: 0.35%
codecov: 
  notify:
    after_n_builds: 26
comment:
  after_n_builds: 26
  layout: "condensed_header, flags, files, condensed_footer"
  hide_project_coverage: true

ignore:
  - "crmsh/report"
