coverage:
  status:
    project:
      default:
        threshold: 0.35%
    patch:
      default:
        threshold: 0.35%
codecov: 
  notify:
    after_n_builds: 27
comment:
  after_n_builds: 27
  layout: "condensed_header, flags, files, condensed_footer"

ignore:
  - "crmsh/report"
