coverage:
  status:
    project:
      default:
        threshold: 0.35%
    patch:
      default:
        threshold: 0.35%
codecov: 
  notify:
    after_n_builds: 23
comment:
  after_n_builds: 23

ignore:
  - "crmsh/report"
