#!/usr/bin/python
#
# Copyright (C) 2008-2015 Dejan Muhamedagic <dmuhamedagic@suse.de>
# Copyright (C) 2013-2015 Kristoffer Gronlund <kgronlund@suse.com>
# See COPYING for license information.
#

import sys
from distutils import version

minimum_version = '2.6'
v_min = version.StrictVersion(minimum_version)
v_this = version.StrictVersion(sys.version[:3])
if v_min > v_this:
    sys.stderr.write("abort: minimum python version support is %s\n" %
                     minimum_version)
    sys.exit(-1)

try:
    try:
        from crmsh import main
    except ImportError as msg:
        try:
            # Perhaps we're running from the source directory
            import modules
            sys.modules['crmsh'] = sys.modules['modules']
            from crmsh import main
        except ImportError as msg2:
            sys.stderr.write('''Fatal error:
        %s
        %s

    Failed to start crmsh! This is likely due to a broken
    installation or a missing dependency.

    If you are using a packaged version of crmsh, please try
    reinstalling the package. Also check your PYTHONPATH and
    make sure that the crmsh module is reachable.

    Please file an issue describing your installation at
    https://github.com/Clusterlabs/crmsh/issues/ .
''' % (msg, msg2))
            sys.exit(-1)
except AttributeError as msg:
    sys.stderr.write('''Fatal error: %s

    Failed to start crmsh! This is likely due to having
    configured Python 3 as the default python version.
    crmsh requires Python 2.6 or higher, but not (yet)
    Python 3.
''' % (msg))
    sys.exit(-1)

rc = main.run()
sys.exit(rc)
# vim:ts=4:sw=4:et:
