#!/usr/bin/python
#
# crmsh, command line interface for Linux HA clusters
# Copyright (C) 2008-2015 Dejan Muhamedagic <dmuhamedagic@suse.de>
# Copyright (C) 2013-2015 Kristoffer Gronlund <kgronlund@suse.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

import sys
from distutils import version

minimum_version = '2.7'
v_min = version.StrictVersion(minimum_version)
v_this = version.StrictVersion(sys.version[:3])
if v_min > v_this:
    sys.stderr.write("abort: minimum python version support is %s\n" %
                     minimum_version)
    sys.exit(-1)

try:
    try:
        from crmsh import main
    except ImportError as msg:
        sys.stderr.write('''Fatal error:
        %s

    Failed to start crmsh! This is likely due to a broken
    installation or a missing dependency.

    If you are using a packaged version of crmsh, please try
    reinstalling the package. Also check your PYTHONPATH and
    make sure that the crmsh module is reachable.

    Please file an issue describing your installation at
    https://github.com/Clusterlabs/crmsh/issues/ .
''' % (msg))
        sys.exit(-1)
except AttributeError as msg:
    sys.stderr.write('''Fatal error: %s

    Failed to start crmsh! This is likely due to having
    configured Python 3 as the default python version.
    crmsh requires Python 2.6 or higher, but not (yet)
    Python 3.
''' % (msg))
    sys.exit(-1)

rc = main.run()
sys.exit(rc)
# vim:ts=4:sw=4:et:
