#!/usr/bin/python3
import os
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from hb_report import core

if __name__ == "__main__":
    try:
        core.ctx = core.Context()
        core.ctx.name = os.path.basename(__file__)
        core.run(core.ctx)
    except KeyboardInterrupt:
        print("\nCtrl-C, leaving")
        sys.exit(1)
