---

name: 1.3.6
group: SBD
labels: generic
description: |
  SBD `msgwait` timeout value is two times the watchdog timeout
remediation: |
  ## Remediation
  Make sure you configure your the SBD msgwait to 2 * (SBD Watchdog Timeout) as recommended on the best practices.

  ## References
  -  https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker#set-up-sbd-device
implementation: "{{ lookup('file', 'roles/checks/'+name+'/tasks/main.yml') }}"

# check id. This value must not be changed over the life of this check
id: 68626E
