---

name: 2.2.5
group: OS and package versions
labels: hana
description: |
  SBD version is supported
remediation: |
  ## Abstract
  Installed SBD version must be equal or higher than {{ expected['2.2.5'] }}

  ## Remediation
  Install or upgrade to a supported SBD version

  ## Reference
  - https://documentation.suse.com/en-us/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/
implementation: "{{ lookup('file', 'roles/checks/'+name+'/tasks/main.yml') }}"

# check id. This value must not be changed over the life of this check
id: 222A57
