---

name: 1.1.8
group: Corosync
labels: generic
description: |
  Corosync `two_node` is set to `{{ expected[name] }}`
remediation: |
  ## Abstract
  The runtime value of the corosync `two_node` parameter is not set as recommended.

  ## Remediation
  Adjust the corosync two_node parameter to `1` to make sure Pacemaker calculates the actions properly for a two-node cluster.

  ## References
  - https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker
implementation: "{{ lookup('file', 'roles/checks/'+name+'/tasks/main.yml') }}"

# Test data
key_name: two_node

# check id. This value must not be changed over the life of this check
id: 6E9B82
