:man source:   crmsh_hb_report
:man version:  1.2
:man manual:   Pacemaker documentation

crmsh_hb_report(8)
==================

NAME
----
crmsh_hb_report - create report for CRM based clusters (Pacemaker)


SYNOPSIS
--------
*crm report* [-f time][-t time][-b time][-u user][-n node][-E file][-p patt][-L patt]
       [-X ssh-options][-MQSZsvhd][dest]


DESCRIPTION
-----------
The crmsh_hb_report(8) is a utility to collect all information (logs,
configuration files, system information, etc) relevant to
Pacemaker (CRM) over the given period of time.


OPTIONS
-------
dest::
	The report name. It can also contain a path where to put the
	report tarball. If left out, the tarball is created in the
	current directory named "hb_report-current_date", for instance
	hb_report-Wed-03-Mar-2010.

*-h*::
	Show usage and some examples.

*-f* time::
	The start time from which to collect logs. 
        Default: 12 hours before.

*-t* time::
	The end time to which to collect logs. Defaults to now.

*-b* time::
	how long time in the past, before now ([1-9][0-9]*[YmdHM]).

*-d*::
	Don't create the compressed tar, but leave the result in a
	directory.

*-n* node::
	A list of space separated hostnames (cluster members).
	crm report may try to find out the set of nodes by itself, but
	if it runs on the loghost which, as it is usually the case,
	does not belong to the cluster, that may be difficult. This 
        option is additive (use -n a -n b or -n "a b").

*-u* user::
	The ssh user. `crm report` will try to login to other nodes
	without specifying a user, then as "root", and finally as
	"hacluster". If you have another user for administration over
	ssh, please use this option.

*-X* ssh-options::
	Extra ssh options (default: StrictHostKeyChecking=no EscapeChar=none 
        ConnectTimeout=15). These will be added to every ssh invocation. 
        Alternatively, use `$HOME/.ssh/config` to setup desired ssh connection options.
        This option is additive (use -X opt1 -X opt2 or -X "opt1 opt2").

*-E* file::
        Extra logs to collect (default: /var/log/messages, 
        /var/log/ha-cluster-bootstrap.log); this option is additive 
        (use -E file1 -E file2 or -E "file1 file2")

*-s* ::
        Replace sensitive info in PE or CIB or pacemaker log files.

*-p* patt::
	Additional patterns to match parameter name which contain
	sensitive information (default: "passw.*").
        This option is additive (use -p patt1 -p patt2 or -p "patt1 patt2").

*-L* patt::
	A list of regular expressions to match in log files for
	analysis (default: "CRIT:, ERROR:, error:, warning:, crit:").
        This option is additive (use -L patt1 -L patt2 or -L "patt1 patt2").

*-Q*::
	Quick run. Gathering some system information can be expensive.
	With this option, such operations are skipped and thus
	information collecting speed up. The operations considered
	I/O or CPU intensive: verifying installed packages content,
	sanitizing files for sensitive information, and producing dot
	files from PE inputs.

*-M*::
	Don't collect extra log files, but only the file containing
	messages from the cluster subsystems.

*-Z*::
	If the destination directory exist, remove it instead of
	exiting.
*-S*::
	Single node operation. Run `crm report` only on this node and
	don't try to start slave collectors on other members of the
	cluster. Under normal circumstances this option is not
	needed. Use if ssh(1) does not work to other nodes.

*-v*::
	Increase verbosity. Normally used to debug unexpected
	behaviour. "-vv" will show more details debug messages.


EXAMPLES
--------
Examples

  # collect from 2pm, today
  hb_report -f 2pm report_1

  # collect from "2007/9/5 12:30" to "2007/9/5 14:00"
  hb_report -f "2007/9/5 12:30" -t "2007/9/5 14:00" report_2

  # collect from 1:00 to 3:00, today; include /var/log/cluster/ha-debug as extra log
  hb_report -f 1:00 -t 3:00 -E /var/log/cluster/ha-debug report_3

  # collect from "09sep07 2:00" and use 'hacluster' as ssh user
  hb_report -f "09sep07 2:00" -u hacluster report_4

  # collect from 18:00, today; replace sensitive message like "usern.*" or "admin.*"
  hb_report -f 18:00 -s -p "usern.*" -p "admin.*" report_5

  # collect from 1 mounth ago
  hb_report -b 1m

  # collect from 12 days ago
  hb_report -b 12d

  # collect from 75 hours ago
  hb_report -b 75H

  # collect from 10 minutes ago
  hb_report -b 10M


INTERPRETIN RESULTS
--------------------
The compressed tar archive is the final product of `crm report`.
This is one example of its content, from a two nodes cluster:

	$ ls -RF hb_report-Sun-01-Mar-2020
        hb_report-Sun-01-Mar-2020:
        15sp1-1/  15sp1-2/  analysis.txt  corosync.conf  members.txt  sysinfo.txt

        hb_report-Sun-01-Mar-2020/15sp1-1:
        cib.txt  context.txt	 crm_mon.txt  dlm_dump.txt  ha-cluster-bootstrap.log  journal.log   ocfs2.txt	   pengine/	    RUNNING  sbd.txt	   sysstats.txt
        cib.xml  corosync.conf@  DC	      events.txt    ha-log.txt		      members.txt@  pacemaker.log  permissions.txt  sbd      sysinfo.txt@  time.txt

        hb_report-Sun-01-Mar-2020/15sp1-1/pengine:
        pe-input-5.bz2	pe-input-5.dot

        hb_report-Sun-01-Mar-2020/15sp1-2:
        cib.txt  context.txt	 crm_mon.txt   events.txt		 ha-log.txt   members.txt@  permissions.txt  sbd      sysinfo.txt@  time.txt
        cib.xml  corosync.conf@  dlm_dump.txt  ha-cluster-bootstrap.log  journal.log  ocfs2.txt     RUNNING	     sbd.txt  sysstats.txt

The top directory contains information which pertains to the
cluster as a whole. Files with exactly the same content on all nodes 
will also be at the top, with per-node links created (as it is in 
this example the case with corosync.conf).

Most files are copied verbatim or they contain output of a
command. For instance, cib.xml is a copy of the CIB found in
/var/lib/pacemaker/cib/cib.xml. crm_mon.txt is output of the
crm_mon(8) program.

Some files are result of a more involved processing:

	*analysis.txt*::
	A set of log messages matching user defined patterns (may be
	provided with the -L option).

        *cib.txt*::
        Output of command "crm configure show"

        *context.txt*::
        Debug info only for developers, contain internal attributes values

        *ha-cluster-bootstrap.log*::
        The log generated by "ha-cluster-*" commands

        *ha-log.txt*::
        Include pacemaker, corosync and sbd logs from journal log

        *pacemaker.log*::
        Compared to messages logged via syslog, messages in this file may 
        have extended information, and will include messages of "info" severity 
        (and, if debug and/or trace logging has been enabled, those as well). 
        This log is of more use to developers and advanced system administrators, 
        and when reporting problems

	*events.txt*::
	A set of log messages matching event patterns. It should
	provide information about major cluster motions without
	unnecessary details.  These patterns are devised by the
	cluster experts.  Currently, the patterns cover membership
	and quorum changes, resource starts and stops, fencing
	(stonith) actions, and cluster starts and stops. events.txt
	is always generated for each node.

	*permissions.txt*::
	One of the more common problem causes are file and directory
	permissions. `crm report` looks for a set of predefined
	directories and checks their permissions. Any issues are
	reported here.

	*sysinfo.txt*::
	Various release information about the platform, kernel,
	operating system, packages, and anything else deemed to be
	relevant. The static part of the system.

	*sysstats.txt*::
	Output of various system commands such as ps(1), uptime(1),
	netstat(8), and ip(8). The dynamic part of the system.

PREREQUISITES
-------------

ssh::
	It is not strictly required, but you won't regret having a
	password-less ssh. It is not too difficult to setup and will save
	you a lot of time. If you can't have it, for example because your
	security policy does not allow such a thing, or you just prefer
	menial work, then you will have to resort to the semi-manual
	semi-automated report generation. See below for instructions.
	+
	If you need to supply a password for your passphrase/login, then
	always use the `-u` option.
	+
	For extra ssh(1) options, if you're too lazy to setup
	$HOME/.ssh/config, use the `-X` option. Do not forget to put
	the options in quotes.

sudo::
	If the ssh user (as specified with the `-u` option) is other
	than `root`, then `crm report` uses `sudo` to collect the
	information which is readable only by the `root` user. In that
	case it is required to setup the `sudoers` file properly. The
	user (or group to which the user belongs) should have the
	following line:
	+
	<user> ALL = NOPASSWD: /usr/sbin/crm
	+
	See the `sudoers(5)` man page for more details.

Should I send all this to the rest of Internet?
-----------------------------------------------

By default, the sensitive data in CIB and PE files is not mangled
by `crm report` because that makes PE input files mostly useless.
If you still have no other option but to send the report to a
public mailing list and do not want the sensitive data to be
included, use the `-s` option. Without this option, `crm report`
will issue a warning if it finds information which should not be
exposed. By default, parameters matching 'passw.*' are considered
sensitive.  Use the `-p` option to specify additional regular
expressions to match variable names which may contain information
you don't want to leak. For example:

	# crm report -f 18:00 -s -p "user.*" -p "secret.*" /var/tmp/report

LOGS
----
`crm report` supports also archived logs in case the period
specified extends that far in the past. The archives must reside
in the same directory as the current log and their names must
be prefixed with the name of the current log (syslog-1.gz or
messages-20090105.bz2).

If there is no separate log for the cluster, possibly unrelated
messages from other programs are included. We don't filter logs,
but just pick a segment for the period you specified.

MANUAL REPORT COLLECTION
------------------------

So, your ssh doesn't work. In that case, you will have to run
this procedure on all nodes. Use `-S` so that `crm report` doesn't
bother with ssh:

	# crm report -f 5:20pm -t 5:30pm -S /tmp/report_node1

If you also have a log host which is not in the cluster, then
you'll have to copy the log to one of the nodes and tell us where
it is:

	# crm report -f 5:20pm -t 5:30pm -E /var/tmp/ha-log -S /tmp/report_node1

OPERATION
---------
`crm report` collects files and other information in a fairly
straightforward way. The most complex tasks are discovering the
log file locations (if syslog is used which is the most common
case) and coordinating the operation on multiple nodes.

The instance of `crm report` running on the host where it was
invoked is the master instance. Instances running on other nodes
are slave(collecter) instances. The master instance communicates 
with slave instances by ssh. There are multiple ssh invocations 
per run, so it is essential that the ssh works without password, 
i.e. with the public key authentication and authorized_keys.

The operation consists of three phases. Each phase must finish
on all nodes before the next one can commence. The first phase
consists of logging unique messages through syslog on all nodes.
This is the shortest of all phases.

The second phase is the most involved. During this phase all
local information is collected, which includes:

- logs (both current and archived if the start time is far in the past)
- various configuration files (corosync, heartbeat, logd)
- the CIB (both as xml and as represented by the crm shell)
- pengine inputs (if this node was the DC at any point in
  time over the given period)
- system information and status
- package information and status
- dlm lock information
- sbd information
- ocfs2 information
- core dump files

The third phase is collecting information from all nodes and
analyzing it. The analyzis consists of the following tasks:

- identify files equal on all nodes which may then be moved to
  the top directory
- save log messages matching user defined patterns
  (defaults to ERRORs and CRITical conditions)
- report if there were coredumps and by whom
- report crm_verify(8) results


BUGS
----
Finding logs may at times be extremely difficult, depending on
how weird the syslog configuration. It would be nice to ask
syslog-ng developers to provide a way to find out the log
destination based on facility and priority.

If you think you found a bug, please rerun with the -v option and
attach the output to bugzilla.

`crm report` can function in a satisfactory way only if ssh works to
all nodes using authorized_keys (without password).

There are way too many options.


AUTHOR
------
Written by Dejan Muhamedagic, <dejan@suse.de>
           Xin Liang, <xliang@suse.com>


RESOURCES
---------
ClusterLabs: <http://clusterlabs.org/>

Crmsh: <https://github.com/ClusterLabs/crmsh/>

Corosync: <http://www.corosync.org/>


SEE ALSO
--------
crm(8)


COPYING
-------
Copyright \(C) 2007-2020 Dejan Muhamedagic and Xin Liang. Free use of this
software is granted under the terms of the GNU General Public License (GPL).

