FROM docker.io/alpine:3.19.0

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
RUN apk add --no-cache \
    py3-lxml \
    py3-yaml \
    py3-dateutil\
    bash \
    make \
    asciidoctor \
    asciidoc


env PYTHONPATH=/opt/crmsh
env PATH=/opt/crmsh/bin:/opt/crmsh/doc/toolchain/bin:"${PATH}"

WORKDIR /opt/crmsh/doc
CMD make
