---

- name: "{{ name }}.check"
  shell: |
    # if hacluster passwd is linux, fail
    salt=$(sudo getent shadow hacluster | cut -d$ -f3)
    epassword=$(sudo getent shadow hacluster | cut -d: -f2)
    match=$(python3 -c 'import crypt; print(crypt.crypt("linux", "$6$'${salt}'"))')
    [[ ${match} == ${epassword} ]] && exit 1
    exit 0
  check_mode: false
  register: config_updated
  changed_when: config_updated.rc != 0
  failed_when: config_updated.rc > 1

- block:
    - name: Post results
      import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is not changed }}"
