.TRY Configuration bugs
.INP: options
.INP: sort_elements false
WARNING: 2: This command 'sort_elements' is deprecated, please use 'sort-elements'
INFO: 2: "sort_elements" is accepted as "sort-elements"
.INP: up
.INP: configure
.INP: erase
.INP: primitive st stonith:null 	params hostlist='node1' 	meta description="some description here" requires=nothing 	op monitor interval=60m
.EXT crm_resource --show-metadata stonith:null
.EXT stonithd metadata
.INP: primitive p4 Dummy
.EXT crm_resource --show-metadata ocf:heartbeat:Dummy
.INP: primitive p3 Dummy
.INP: primitive p2 Dummy
.INP: primitive p1 Dummy
.INP: colocation c1 inf: p1 p2
.INP: filter "sed 's/p1 p2/& p3/'" c1
.INP: show c1
colocation c1 inf: p1 p2 p3
.INP: delete c1
.INP: colocation c2 inf: [ p1 p2 ] p3 p4
.INP: filter "sed 's/\[/\(/;s/\]/\)/'" c2
.INP: show c2
colocation c2 inf: ( p1 p2 ) p3 p4
.INP: primitive p5 Dummy
.INP: primitive p6 Dummy
.INP: clone cl-p5 p5
.INP: show
node node1
primitive st stonith:null \
	params hostlist=node1 \
	meta description="some description here" requires=nothing \
	op monitor interval=60m timeout=20s \
        op start timeout=20s interval=0s \
        op stop timeout=15s interval=0s
primitive p4 Dummy \
        op monitor timeout=20s interval=10s \
        op start timeout=20s interval=0s \
        op stop timeout=20s interval=0s
primitive p3 Dummy \
        op monitor timeout=20s interval=10s \
        op start timeout=20s interval=0s \
        op stop timeout=20s interval=0s
primitive p2 Dummy \
        op monitor timeout=20s interval=10s \
        op start timeout=20s interval=0s \
        op stop timeout=20s interval=0s
primitive p1 Dummy \
        op monitor timeout=20s interval=10s \
        op start timeout=20s interval=0s \
        op stop timeout=20s interval=0s
primitive p5 Dummy \
        op monitor timeout=20s interval=10s \
        op start timeout=20s interval=0s \
        op stop timeout=20s interval=0s
primitive p6 Dummy \
        op monitor timeout=20s interval=10s \
        op start timeout=20s interval=0s \
        op stop timeout=20s interval=0s
clone cl-p5 p5 \
       meta interleave=true
colocation c2 inf: ( p1 p2 ) p3 p4
.INP: commit
.INP: _test
.INP: verify
.INP: show
node node1
primitive st stonith:null \
	params hostlist=node1 \
	meta description="some description here" requires=nothing \
	op monitor interval=60m timeout=20s \
        op start timeout=20s interval=0s \
        op stop timeout=15s interval=0s
primitive p4 Dummy \
        op monitor timeout=20s interval=10s \
        op start timeout=20s interval=0s \
        op stop timeout=20s interval=0s
primitive p3 Dummy \
        op monitor timeout=20s interval=10s \
        op start timeout=20s interval=0s \
        op stop timeout=20s interval=0s
primitive p2 Dummy \
        op monitor timeout=20s interval=10s \
        op start timeout=20s interval=0s \
        op stop timeout=20s interval=0s
primitive p1 Dummy \
        op monitor timeout=20s interval=10s \
        op start timeout=20s interval=0s \
        op stop timeout=20s interval=0s
primitive p6 Dummy \
        op monitor timeout=20s interval=10s \
        op start timeout=20s interval=0s \
        op stop timeout=20s interval=0s
primitive p5 Dummy \
        op monitor timeout=20s interval=10s \
        op start timeout=20s interval=0s \
        op stop timeout=20s interval=0s
clone cl-p5 p5 \
       meta interleave=true
colocation c2 inf: ( p1 p2 ) p3 p4
.TRY Unordered load file
.INP: options
.INP: sort_elements false
WARNING: 2: This command 'sort_elements' is deprecated, please use 'sort-elements'
INFO: 2: "sort_elements" is accepted as "sort-elements"
.INP: up
.INP: configure
.INP: load update bugs-test.txt
.EXT crm_resource --show-metadata ocf:heartbeat:Dummy
.INP: show
node node1
primitive st stonith:null \
	params hostlist=node1
primitive p4 Dummy \
        op monitor timeout=20s interval=10s \
        op start timeout=20s interval=0s \
        op stop timeout=20s interval=0s
primitive p3 Dummy \
        op monitor timeout=20s interval=10s \
        op start timeout=20s interval=0s \
        op stop timeout=20s interval=0s
primitive p2 Dummy \
        op monitor timeout=20s interval=10s \
        op start timeout=20s interval=0s \
        op stop timeout=20s interval=0s
primitive p1 Dummy \
        op monitor timeout=20s interval=10s \
        op start timeout=20s interval=0s \
        op stop timeout=20s interval=0s
primitive p6 Dummy \
        op monitor timeout=20s interval=10s \
        op start timeout=20s interval=0s \
        op stop timeout=20s interval=0s
primitive p5 Dummy \
        op monitor timeout=20s interval=10s \
        op start timeout=20s interval=0s \
        op stop timeout=20s interval=0s
primitive gr1 Dummy
primitive gr2 Dummy
primitive gr3 Dummy
primitive gr4 Dummy
group g1 gr1 gr2
group g2 gr3
group g3 gr4
clone cl-p5 p5 \
       meta interleave=true
colocation c2 inf: ( p1 p2 ) p3 p4
location loc1 g1 \
	rule 200: #uname eq node1
op_defaults op-options: \
	timeout=60s
.INP: commit
.EXT crm_resource --show-metadata stonith:null
.EXT stonithd metadata
.INP: _test
.INP: verify
.TRY Unknown properties
.INP: configure
.INP: erase
INFO: 2: constraint colocation:c2 updated
INFO: 2: constraint colocation:c2 updated
INFO: 2: modified location:loc1 from g1 to gr2
.INP: primitive st stonith:null 	params hostlist='node1' 	meta description="some description here" requires=nothing 	op monitor interval=60m
.EXT crm_resource --show-metadata stonith:null
.EXT stonithd metadata
.INP: property SAPHanaSR:     hana_ha1_site_lss_WDF1=4
.INP: show
node node1
primitive st stonith:null \
	params hostlist=node1 \
	meta description="some description here" requires=nothing \
	op monitor interval=60m timeout=20s \
        op start timeout=20s interval=0s \
        op stop timeout=15s interval=0s
property SAPHanaSR: \
	hana_ha1_site_lss_WDF1=4
.INP: commit
.INP: _test
.INP: verify
.INP: property SAPHanaSR_2:     hana_ha1_site_iss_WDF1=cde     hana_ha1_site_bss_WDF1=abc
.INP: show
node node1
primitive st stonith:null \
	params hostlist=node1 \
	meta description="some description here" requires=nothing \
	op monitor interval=60m timeout=20s \
        op start timeout=20s interval=0s \
        op stop timeout=15s interval=0s
property SAPHanaSR: \
	hana_ha1_site_lss_WDF1=4
property SAPHanaSR_2: \
	hana_ha1_site_iss_WDF1=cde \
	hana_ha1_site_bss_WDF1=abc
.INP: commit
.INP: _test
.INP: verify
.TRY template
.INP: configure
.INP: erase
.INP: node node1
.INP: primitive st stonith:null 	params hostlist='node1' 	meta description="some description here" requires=nothing 	op monitor interval=60m
.EXT crm_resource --show-metadata stonith:null
.EXT stonithd metadata
.INP: template
.INP: new vip virtual-ip params ip=10.10.10.123
INFO: 6: pulling in template virtual-ip
.INP: load vip
.INP: apply update
.EXT crm_resource --show-metadata ocf:heartbeat:IPaddr
.EXT crm_resource --list-ocf-alternatives IPaddr
.INP: up
.INP: commit
.INP: _test
.INP: verify
