.TRY Basic configure
.INP: configure
.INP: _regtest on
.INP: erase
.INP: erase nodes
.INP: property fencing-enabled=false
.INP: node node1
.INP: delete node1
.INP: node node1 	attributes mem=16G
.INP: node node2 utilization cpu=4
.INP: bundle id=bundle-test1 docker image=test network ip-range-start=10.10.10.123 port-mapping id=port1 port=80 storage storage-mapping id=storage1 target-dir=test source-dir=test meta target-role=Stopped
.INP: primitive id=dummy ocf:heartbeat:Dummy op monitor interval=10 meta target-role=Stopped
.EXT crm_resource --show-metadata ocf:heartbeat:Dummy
.INP: bundle id=bundle-test2 docker image=test network ip-range-start=10.10.10.123 primitive dummy meta target-role=Stopped priority=1
.INP: _test
.INP: verify
.EXT crm_attribute --list-options=cluster --all --output-as=xml
.EXT crm_resource --list-options=primitive --all --output-as=xml
.INP: show
node node1 \
       attributes mem=16G
node node2 \
       utilization cpu=4
primitive dummy Dummy \
	meta target-role=Stopped \
	op monitor interval=10s timeout=20s \
	op start timeout=20s interval=0s \
	op stop timeout=20s interval=0s
bundle bundle-test1 \
	docker image=test \
	network ip-range-start=10.10.10.123 \
		port-mapping port=80 \
	storage \
		storage-mapping target-dir=test source-dir=test \
	meta target-role=Stopped
bundle bundle-test2 \
	docker image=test \
	network ip-range-start=10.10.10.123 \
	primitive dummy \
	meta target-role=Stopped priority=1
property cib-bootstrap-options: \
	fencing-enabled=false
.INP: commit
