.TRY Commits of all kinds
.INP: configure
.INP: _regtest on
.INP: erase
.INP: erase nodes
.INP: property fencing-enabled=false
.INP: op_defaults timeout=2m
.INP: commit
.EXT crm_attribute --list-options=cluster --all --output-as=xml
.INP: node node1 	attributes mem=16G
.INP: primitive p1 ocf:heartbeat:Dummy 	op monitor interval=60m 	op monitor interval=120m OCF_CHECK_LEVEL=10
.EXT crm_resource --show-metadata ocf:heartbeat:Dummy
.INP: primitive p2 ocf:heartbeat:Dummy
.INP: primitive p3 ocf:heartbeat:Dummy
.INP: group g1 p1 p2
.INP: clone c1 g1
.INP: location l1 p3 100: node1
.INP: order o1 Mandatory: p3 c1
.INP: colocation cl1 inf: c1 p3
.INP: primitive d1 ocf:heartbeat:Dummy
.INP: primitive d2 ocf:heartbeat:Dummy
.INP: primitive d3 ocf:heartbeat:Dummy
.INP: commit
.EXT crm_resource --list-options=primitive --all --output-as=xml
.INP: rename p3 pp3
INFO: 21: modified location:l1 from p3 to pp3
INFO: 21: modified order:o1 from p3 to pp3
INFO: 21: modified colocation:cl1 from p3 to pp3
.INP: commit
.INP: rename pp3 p3
INFO: 23: modified location:l1 from pp3 to p3
INFO: 23: modified order:o1 from pp3 to p3
INFO: 23: modified colocation:cl1 from pp3 to p3
.INP: delete c1
INFO: 24: modified order:o1 from c1 to g1
INFO: 24: modified colocation:cl1 from c1 to g1
.INP: commit
.INP: group g2 d1 d2
.INP: commit
.INP: delete g2
.INP: commit
.INP: filter "sed '/g1/s/p1/d1/'"
.INP: group g2 d3 d2
.INP: delete d2
.INP: commit
.INP: _test
.INP: verify
.INP: show
node node1 \
	attributes mem=16G
primitive d1 Dummy \
        op monitor timeout=20s interval=10s \
        op start timeout=20s interval=0s \
        op stop timeout=20s interval=0s
primitive d3 Dummy \
        op monitor timeout=20s interval=10s \
        op start timeout=20s interval=0s \
        op stop timeout=20s interval=0s
primitive p1 Dummy \
	op monitor interval=60m timeout=20s \
	op monitor interval=120m timeout=20s \
	op_params OCF_CHECK_LEVEL=10 \
        op start timeout=20s interval=0s \
        op stop timeout=20s interval=0s
primitive p2 Dummy \
        op monitor timeout=20s interval=10s \
        op start timeout=20s interval=0s \
        op stop timeout=20s interval=0s
primitive p3 Dummy \
        op monitor timeout=20s interval=10s \
        op start timeout=20s interval=0s \
        op stop timeout=20s interval=0s
group g1 d1 p2
group g2 d3
colocation cl1 inf: g1 p3
location l1 p3 100: node1
order o1 Mandatory: p3 g1
property cib-bootstrap-options: \
	fencing-enabled=false
op_defaults op-options: \
	timeout=2m
.INP: commit
INFO: 37: apparently there is nothing to commit
INFO: 37: try changing something first
