<?xml version="1.0" ?>
<cib num_updates="1" dc-uuid="f36760d8-d84a-46b2-b452-4c8cac8b3396" crm_feature_set="3.0.1" validate-with="pacemaker-1.1" remote-tls-port="0" epoch="0" admin_epoch="0" have-quorum="1">
  <configuration>
    <crm_config>
      <cluster_property_set id="cib-bootstrap-options">
        <nvpair name="stonith-enabled" value="true" id="cib-bootstrap-options-stonith-enabled"/>
      </cluster_property_set>
      <cluster_property_set id="cpset2">
        <nvpair name="maintenance-mode" value="true" id="cpset2-maintenance-mode"/>
      </cluster_property_set>
    </crm_config>
    <nodes>
      <node uname="node1" id="node1">
        <instance_attributes id="node1-instance_attributes">
          <nvpair name="mem" value="16G" id="node1-instance_attributes-mem"/>
        </instance_attributes>
      </node>
      <node uname="pingnode" type="ping" id="pingnode"/>
    </nodes>
    <resources>
      <primitive id="d6" class="ocf" provider="pacemaker" type="Dummy">
        <operations id-ref="d1-ops"/>
      </primitive>
      <group id="g1">
        <primitive id="d1" class="ocf" provider="pacemaker" type="Dummy">
          <operations id="d1-ops">
            <op name="monitor" interval="60m" id="d1-monitor-60m"/>
            <op name="monitor" interval="120m" id="d1-monitor-120m">
              <instance_attributes id="d1-monitor-120m-instance_attributes">
                <nvpair name="OCF_CHECK_LEVEL" value="10" id="d1-monitor-120m-instance_attributes-OCF_CHECK_LEVEL"/>
              </instance_attributes>
            </op>
            <op interval="60s" timeout="30s" name="monitor" id="d1-monitor-60s"/>
          </operations>
        </primitive>
        <primitive id="d2" class="ocf" provider="heartbeat" type="Delay">
          <instance_attributes id="d2-instance_attributes">
            <nvpair name="mondelay" value="60" id="d2-instance_attributes-mondelay"/>
          </instance_attributes>
          <operations>
            <op name="start" timeout="60s" interval="0" id="d2-start-0"/>
            <op name="stop" timeout="60s" interval="0" id="d2-stop-0"/>
            <op role="Started" interval="60s" timeout="30s" name="monitor" id="d2-monitor-60s"/>
          </operations>
        </primitive>
      </group>
      <master id="m">
        <primitive id="d4" class="ocf" provider="pacemaker" type="Dummy"/>
      </master>
      <primitive id="d5" class="ocf" provider="pacemaker" type="Dummy">
        <operations id-ref="d1-ops"/>
      </primitive>
      <clone id="c">
        <meta_attributes id="c-meta_attributes">
          <nvpair name="clone-max" value="1" id="c-meta_attributes-clone-max"/>
        </meta_attributes>
        <primitive id="d3" class="ocf" provider="pacemaker" type="Dummy"/>
      </clone>
      <primitive id="st" class="stonith" type="ssh">
        <instance_attributes id="st-instance_attributes">
          <nvpair name="hostlist" value="node1" id="st-instance_attributes-hostlist"/>
        </instance_attributes>
        <meta_attributes id="st-meta_attributes">
          <nvpair name="target-role" value="Started" id="st-meta_attributes-target-role"/>
        </meta_attributes>
        <operations>
          <op name="start" requires="nothing" timeout="60s" interval="0" id="st-start-0"/>
          <op name="monitor" interval="60m" timeout="60s" id="st-monitor-60m"/>
        </operations>
      </primitive>
    </resources>
    <constraints>
      <rsc_order id="o4" score="INFINITY" first="d5" then="d6"/>
      <rsc_ticket id="ticket-C_master" ticket="ticket-C" loss-policy="fence">
        <resource_set id="ticket-C_master-0">
          <resource_ref id="d6"/>
        </resource_set>
        <resource_set id="ticket-C_master-1" role="Master">
          <resource_ref id="d5"/>
        </resource_set>
      </rsc_ticket>
      <rsc_ticket id="ticket-A_d6" ticket="ticket-A" rsc="d6"/>
      <rsc_ticket id="ticket-B_d6_d5" ticket="ticket-B" loss-policy="fence">
        <resource_set id="ticket-B_d6_d5-0">
          <resource_ref id="d6"/>
          <resource_ref id="d5"/>
        </resource_set>
      </rsc_ticket>
      <rsc_location id="l4" rsc="d5">
        <rule score="-INFINITY" boolean-op="or" id="l4-rule">
          <expression operation="not_defined" attribute="pingd" id="l4-expression"/>
          <expression attribute="pingd" operation="lte" value="0" id="l4-expression-0"/>
        </rule>
      </rsc_location>
      <rsc_location id="l3" rsc="d5">
        <rule score="INFINITY" id="l3-rule">
          <expression attribute="#uname" operation="eq" value="node1" id="l3-expression"/>
          <expression attribute="pingd" operation="gt" value="0" id="l3-expression-0"/>
        </rule>
      </rsc_location>
      <rsc_location id="l5" rsc="d5">
        <rule score="-INFINITY" boolean-op="or" id="l5-rule">
          <expression operation="not_defined" attribute="pingd" id="l5-expression"/>
          <expression attribute="pingd" operation="lte" value="0" id="l5-expression-0"/>
        </rule>
        <rule score="INFINITY" id="l5-rule-0">
          <expression attribute="#uname" operation="eq" value="node1" id="l5-expression-1"/>
          <expression attribute="pingd" operation="gt" value="0" id="l5-expression-2"/>
        </rule>
        <rule score="INFINITY" id="l5-rule-1">
          <date_expression operation="lt" id="l5-expression-3" end="2009-05-26"/>
          <date_expression operation="in_range" id="l5-expression-4" start="2009-05-26" end="2009-07-26"/>
          <date_expression operation="in_range" id="l5-expression-5" start="2009-05-26">
            <duration id="l5-duration" years="2009"/>
          </date_expression>
          <date_expression operation="date_spec" id="l5-expression-6">
            <date_spec id="l5-date_spec" years="2009" hours="09-17"/>
          </date_expression>
        </rule>
      </rsc_location>
      <rsc_location id="l1" rsc="g1" score="100" node="node1"/>
      <rsc_location id="l2" rsc="c">
        <rule id="l2-rule1" score="100">
          <expression attribute="#uname" operation="eq" value="node1" id="l2-expression"/>
        </rule>
      </rsc_location>
      <rsc_location id="l6" rsc="d5">
        <rule id-ref="l2-rule1"/>
      </rsc_location>
      <rsc_order id="o3" kind="Serialize" first="d5" then="d6"/>
      <rsc_colocation id="c2" score="INFINITY" rsc="d5" rsc-role="Started" with-rsc="d6" with-rsc-role="Started"/>
      <rsc_order id="o2" kind="Optional" first="d5" first-action="start" then="d6" then-action="promote"/>
      <rsc_location id="l7" rsc="d5">
        <rule id-ref="l2-rule1"/>
      </rsc_location>
      <rsc_colocation id="c1" score="INFINITY" rsc="d5" with-rsc="d6"/>
      <rsc_order id="o1" kind="Mandatory" first="d5" then="d6"/>
    </constraints>
    <op_defaults>
      <meta_attributes id="opsdef2">
        <nvpair name="record-pending" value="true" id="opsdef2-record-pending"/>
      </meta_attributes>
    </op_defaults>
    <rsc_defaults>
      <meta_attributes id="rsc-options">
        <nvpair name="failure-timeout" value="10m" id="rsc-options-failure-timeout"/>
      </meta_attributes>
    </rsc_defaults>
  </configuration>
</cib>
