.TRY Delete/Rename test
.INP: configure
.INP: # erase to start from scratch
.INP: erase
.INP: erase nodes
.INP: property fencing-enabled=false
.INP: node node1
.INP: primitive d1 ocf:pacemaker:Dummy
.EXT crm_resource --show-metadata ocf:pacemaker:Dummy
.INP: primitive d2 ocf:pacemaker:Dummy
.INP: location d1-pref d1 100: node1
.INP: show
node node1
primitive d1 ocf:pacemaker:Dummy \
	op monitor timeout=20s interval=10s \
	op start timeout=20s interval=0s \
	op stop timeout=20s interval=0s
primitive d2 ocf:pacemaker:Dummy \
	op monitor timeout=20s interval=10s \
	op start timeout=20s interval=0s \
	op stop timeout=20s interval=0s
location d1-pref d1 100: node1
property cib-bootstrap-options: \
	fencing-enabled=false
.INP: _test
.INP: rename d1 p1
INFO: 12: modified location:d1-pref from d1 to p1
.INP: show
node node1
primitive d2 ocf:pacemaker:Dummy \
	op monitor timeout=20s interval=10s \
	op start timeout=20s interval=0s \
	op stop timeout=20s interval=0s
primitive p1 ocf:pacemaker:Dummy \
	op monitor timeout=20s interval=10s \
	op start timeout=20s interval=0s \
	op stop timeout=20s interval=0s
location d1-pref p1 100: node1
property cib-bootstrap-options: \
	fencing-enabled=false
.INP: # delete primitive
.INP: delete d2
.INP: _test
.INP: show
node node1
primitive p1 ocf:pacemaker:Dummy \
	op monitor timeout=20s interval=10s \
	op start timeout=20s interval=0s \
	op stop timeout=20s interval=0s
location d1-pref p1 100: node1
property cib-bootstrap-options: \
	fencing-enabled=false
.INP: # delete primitive with constraint
.INP: delete p1
INFO: 19: hanging location:d1-pref deleted
.INP: _test
.INP: show
node node1
property cib-bootstrap-options: \
	fencing-enabled=false
.INP: primitive d1 ocf:pacemaker:Dummy
.INP: location d1-pref d1 100: node1
.INP: _test
.INP: # delete primitive belonging to a group
.INP: primitive d2 ocf:pacemaker:Dummy
.INP: _test
.INP: group g1 d2 d1
INFO: 28: modified location:d1-pref from d1 to g1
.INP: delete d2
.INP: show
node node1
primitive d1 ocf:pacemaker:Dummy \
	op monitor timeout=20s interval=10s \
	op start timeout=20s interval=0s \
	op stop timeout=20s interval=0s
group g1 d1
location d1-pref g1 100: node1
property cib-bootstrap-options: \
	fencing-enabled=false
.INP: _test
.INP: delete g1
INFO: 32: modified location:d1-pref from g1 to d1
.INP: show
node node1
primitive d1 ocf:pacemaker:Dummy \
	op monitor timeout=20s interval=10s \
	op start timeout=20s interval=0s \
	op stop timeout=20s interval=0s
location d1-pref d1 100: node1
property cib-bootstrap-options: \
	fencing-enabled=false
.INP: verify
.EXT crm_attribute --list-options=cluster --all --output-as=xml
.EXT crm_resource --list-options=primitive --all --output-as=xml
.INP: # delete a group which is in a clone
.INP: primitive d2 ocf:pacemaker:Dummy
.INP: group g1 d2 d1
INFO: 37: modified location:d1-pref from d1 to g1
.INP: clone c1 g1
INFO: 38: modified location:d1-pref from g1 to c1
.INP: delete g1
INFO: 39: modified location:d1-pref from c1 to g1
INFO: 39: modified location:d1-pref from g1 to d2
.INP: show
node node1
primitive d1 ocf:pacemaker:Dummy \
	op monitor timeout=20s interval=10s \
	op start timeout=20s interval=0s \
	op stop timeout=20s interval=0s
primitive d2 ocf:pacemaker:Dummy \
	op monitor timeout=20s interval=10s \
	op start timeout=20s interval=0s \
	op stop timeout=20s interval=0s
location d1-pref d2 100: node1
property cib-bootstrap-options: \
	fencing-enabled=false
.INP: _test
.INP: group g1 d2 d1
INFO: 42: modified location:d1-pref from d2 to g1
.INP: clone c1 g1
INFO: 43: modified location:d1-pref from g1 to c1
.INP: _test
.INP: # delete group from a clone (again)
.INP: delete g1
INFO: 46: modified location:d1-pref from c1 to g1
INFO: 46: modified location:d1-pref from g1 to d2
.INP: show
node node1
primitive d1 ocf:pacemaker:Dummy \
	op monitor timeout=20s interval=10s \
	op start timeout=20s interval=0s \
	op stop timeout=20s interval=0s
primitive d2 ocf:pacemaker:Dummy \
	op monitor timeout=20s interval=10s \
	op start timeout=20s interval=0s \
	op stop timeout=20s interval=0s
location d1-pref d2 100: node1
property cib-bootstrap-options: \
	fencing-enabled=false
.INP: _test
.INP: group g1 d2 d1
INFO: 49: modified location:d1-pref from d2 to g1
.INP: clone c1 g1
INFO: 50: modified location:d1-pref from g1 to c1
.INP: # delete primitive and its group and their clone
.INP: delete d2 d1 c1 g1
INFO: 52: modified location:d1-pref from c1 to g1
INFO: 52: modified location:d1-pref from g1 to d2
INFO: 52: hanging location:d1-pref deleted
.INP: show
node node1
property cib-bootstrap-options: \
	fencing-enabled=false
.INP: _test
.INP: # verify
.INP: verify
.INP: commit
