.TRY Configuration editing
.INP: configure
.INP: _regtest on
.INP: erase
.INP: erase nodes
.INP: property default-action-timeout=2m
.INP: node node1 	attributes mem=16G
.INP: primitive st stonith:null 	params hostlist='node1' 	meta description="some description here" 	op start requires=nothing 	op monitor interval=60m
.INP: primitive p1 ocf:heartbeat:Dummy 	op monitor interval=60m 	op monitor interval=120m OCF_CHECK_LEVEL=10
.INP: filter "sed '$aprimitive p2 ocf:heartbeat:Dummy'"
.INP: filter "sed '$agroup g1 p1 p2'"
.INP: filter "sed 's/p2/p3/;$aprimitive p3 ocf:heartbeat:Dummy'" g1
.INP: filter "sed '$aclone c1 p2'"
.INP: filter "sed 's/p2/g1/'" c1
.INP: filter "sed '/clone/s/g1/p2/'" c1 g1
.INP: filter "sed '/clone/s/p2/g1/;s/p3/p2/'" c1 g1
ERROR: 15: p2 already in use at c1
.INP: filter "sed '1,$d'" c1 g1
.INP: filter "sed -e '$aclone c1 g1' -e '$agroup g1 p1 p2'"
.INP: location l1 p3 100: node1
.INP: order o1 inf: p3 c1
.INP: colocation cl1 inf: c1 p3
.INP: filter "sed '/cl1/s/p3/p2/'"
.INP: filter "sed '/cl1/d'"
.INP: primitive d1 ocf:heartbeat:Dummy
.INP: primitive d2 ocf:heartbeat:Dummy
.INP: primitive d3 ocf:heartbeat:Dummy
.INP: group g2 d1 d2
.INP: filter "sed '/g2/s/d1/p1/;/g1/s/p1/d1/'"
ERROR: 27: d1 already in use at g2
ERROR: 27: p1 already in use at g1
.INP: filter "sed '$alocation loc-d1 d1 rule $id=r1 -inf: not_defined webserver rule $id=r2 webserver: defined webserver'"
.INP: filter "sed 's/not_defined webserver/& or mem number:lte 0/'" loc-d1
.INP: filter "sed 's/ or mem number:lte 0//'" loc-d1
.INP: filter "sed 's/not_defined webserver/& rule -inf: not_defined a2/'" loc-d1
.INP: filter "sed 's/not_defined webserver/& or mem number:lte 0/'" loc-d1
.INP: _test
.INP: verify
.INP: show
node node1 \
	attributes mem="16G"
primitive d1 ocf:heartbeat:Dummy
primitive d2 ocf:heartbeat:Dummy
primitive d3 ocf:heartbeat:Dummy
primitive p1 ocf:heartbeat:Dummy \
	op monitor interval="60m" \
	op monitor interval="120m" OCF_CHECK_LEVEL="10"
primitive p2 ocf:heartbeat:Dummy
primitive p3 ocf:heartbeat:Dummy
primitive st stonith:null \
	params hostlist="node1" \
	meta description="some description here" \
	op start interval="0" requires="nothing" \
	op monitor interval="60m"
group g1 p1 p2
group g2 d1 d2
clone c1 g1
location l1 p3 100: node1
location loc-d1 d1 \
	rule $id="r1" -inf: not_defined webserver or mem number:lte 0 \
	rule $id="loc-d1-rule" -inf: not_defined a2 \
	rule $id="r2" webserver: defined webserver
order o1 inf: p3 c1
property $id="cib-bootstrap-options" \
	default-action-timeout="2m"
.INP: commit
