.TRY configure save sample.txt
.EXT cat sample.txt
node node1
primitive p0 ocf:pacemaker:Dummy \
        op monitor timeout=20s interval=10s \
        op start timeout=20s interval=0s \
        op stop timeout=20s interval=0s
primitive p1 ocf:pacemaker:Dummy \
        op monitor timeout=20s interval=10s \
        op start timeout=20s interval=0s \
        op stop timeout=20s interval=0s
primitive p2 Delay \
	params startdelay=2 mondelay=2 stopdelay=2 \
        op monitor timeout=40s interval=10s \
        op start timeout=30s interval=0s \
        op stop timeout=40s interval=0s
primitive p3 ocf:pacemaker:Dummy \
        op monitor timeout=20s interval=10s \
        op start timeout=20s interval=0s \
        op stop timeout=20s interval=0s
clone c1 p1 \
       meta interleave=true
clone m1 p2 \
       meta promotable=true interleave=true
property cib-bootstrap-options: \
	stonith-enabled=false
rsc_defaults build-resource-defaults: \
       resource-stickiness=1
op_defaults op-options: \
	timeout=60s
.TRY configure erase nodes
.TRY configure load replace sample.txt
.EXT crm_resource --show-metadata ocf:pacemaker:Dummy
.EXT crm_resource --show-metadata ocf:heartbeat:Delay
.EXT crm_resource --list-options=primitive --all --output-as=xml
.EXT crm_attribute --list-options=cluster --all --output-as=xml
.EXT sed -i 's/60s/2m/' sample.txt
.EXT sed -i '8a # comment' sample.txt
.TRY Load update
.INP: configure
.INP: delete m1 p1
.INP: property cluster-recheck-interval="10m"
.INP: load update sample.txt
ERROR: 4: syntax: Unknown command near <op> parsing 'op stop timeout=20s interval=0s'
.EXT crm_attribute --list-options=cluster --all --output-as=xml
.TRY configure show
node node1
primitive p0 ocf:pacemaker:Dummy \
        op monitor timeout=20s interval=10s \
        op start timeout=20s interval=0s \
        op stop timeout=20s interval=0s
primitive p2 Delay \
	params startdelay=2 mondelay=2 stopdelay=2 \
        op monitor timeout=40s interval=10s \
        op start timeout=30s interval=0s \
        op stop timeout=40s interval=0s
primitive p3 ocf:pacemaker:Dummy \
        op monitor timeout=20s interval=10s \
        op start timeout=20s interval=0s \
        op stop timeout=20s interval=0s
property cib-bootstrap-options: \
	stonith-enabled=false \
	cluster-recheck-interval=10m
rsc_defaults build-resource-defaults: \
       resource-stickiness=1
op_defaults op-options: \
	timeout=60s
.EXT rm sample.txt
