.TRY configure save sample.txt
.EXT cat sample.txt
node node1
primitive p0 ocf:pacemaker:Dummy
primitive p1 ocf:pacemaker:Dummy
primitive p2 Delay \
	params startdelay=2 mondelay=2 stopdelay=2
primitive p3 ocf:pacemaker:Dummy
primitive st stonith:null \
	params hostlist=node1
clone c1 p1
clone m1 p2 \
       meta promotable=true
rsc_defaults build-resource-defaults: \
       resource-stickiness=1
op_defaults op-options: \
	timeout=60s
.TRY configure erase nodes
.TRY configure load replace sample.txt
.EXT crm_resource --show-metadata ocf:pacemaker:Dummy
.EXT crm_resource --show-metadata ocf:heartbeat:Delay
.EXT crm_resource --show-metadata stonith:null
.EXT stonithd metadata
.EXT sed -i 's/60s/2m/' sample.txt
.EXT sed -i '8a # comment' sample.txt
.TRY Load update
.INP: configure
.INP: delete m1 p1
.INP: property cluster-recheck-interval="10m"
.INP: load update sample.txt
.EXT crm_resource --show-metadata ocf:pacemaker:Dummy
.EXT crm_resource --show-metadata stonith:null
.EXT stonithd metadata
.EXT crm_resource --show-metadata ocf:heartbeat:Delay
.EXT crmd metadata
.EXT pengine metadata
.EXT cib metadata
.TRY configure show
node node1
primitive p0 ocf:pacemaker:Dummy
primitive p1 ocf:pacemaker:Dummy
primitive p2 Delay \
	params startdelay=2 mondelay=2 stopdelay=2
primitive p3 ocf:pacemaker:Dummy
primitive st stonith:null \
	params hostlist=node1
# comment
clone c1 p1
clone m1 p2 \
       meta promotable=true
property cib-bootstrap-options: \
	cluster-recheck-interval=10m
rsc_defaults build-resource-defaults: \
       resource-stickiness=1
op_defaults op-options: \
	timeout=2m
.EXT rm sample.txt
