.TRY configure save sample.txt
.EXT cat sample.txt
node node1
primitive p0 ocf:pacemaker:Dummy
primitive p1 ocf:pacemaker:Dummy
primitive p2 ocf:heartbeat:Delay \
	params startdelay="2" mondelay="2" stopdelay="2"
primitive p3 ocf:pacemaker:Dummy
primitive st stonith:null \
	params hostlist="node1"
ms m1 p2
clone c1 p1
property $id="cib-bootstrap-options" \
	default-action-timeout="60s"
.TRY configure erase nodes
.TRY configure load replace sample.txt
.EXT sed -i 's/60s/2m/' sample.txt
.EXT sed -i '8a # comment' sample.txt
.TRY Load update
.INP: configure
.INP: delete m1 p1
.INP: load update sample.txt
.TRY configure show
node node1
primitive p0 ocf:pacemaker:Dummy
primitive p1 ocf:pacemaker:Dummy
primitive p2 ocf:heartbeat:Delay \
	params startdelay="2" mondelay="2" stopdelay="2"
primitive p3 ocf:pacemaker:Dummy
primitive st stonith:null \
	params hostlist="node1"
# 
ms m1 p2
clone c1 p1
property $id="cib-bootstrap-options" \
	default-action-timeout="2m"
.EXT rm sample.txt
