.TRY node show
.EXT >/dev/null </dev/null crm_shadow 2>&1
node1: normal
.TRY node show node1
.EXT >/dev/null </dev/null crm_shadow 2>&1
node1: normal
.SETENV showobj=node1
.TRY node standby node1
.EXT >/dev/null </dev/null crm_shadow 2>&1
.EXT crm_attribute -t nodes -N 'node1' -n standby -v 'on' --lifetime='forever'
.EXT >/dev/null </dev/null crm_shadow 2>&1
.INP: configure
.INP: _regtest on
.INP: show xml node1
<?xml version="1.0" ?>
<cib admin_epoch="0" epoch="1" num_updates="1" validate-with="pacemaker-1.2" cib-last-written="Sun Apr 12 21:37:48 2009">
  <configuration>
    <crm_config/>
    <nodes>
      <node uname="node1" id="node1">
        <instance_attributes id="nodes-node1">
          <nvpair id="nodes-node1-standby" name="standby" value="on"/>
        </instance_attributes>
      </node>
    </nodes>
    <resources/>
    <constraints/>
  </configuration>
</cib>

.TRY node online node1
.EXT >/dev/null </dev/null crm_shadow 2>&1
.EXT crm_attribute -t nodes -N 'node1' -n standby -v 'off' --lifetime='forever'
.EXT >/dev/null </dev/null crm_shadow 2>&1
.INP: configure
.INP: _regtest on
.INP: show xml node1
<?xml version="1.0" ?>
<cib admin_epoch="0" epoch="1" num_updates="1" validate-with="pacemaker-1.2" cib-last-written="Sun Apr 12 21:37:48 2009">
  <configuration>
    <crm_config/>
    <nodes>
      <node uname="node1" id="node1">
        <instance_attributes id="nodes-node1">
          <nvpair id="nodes-node1-standby" name="standby" value="off"/>
        </instance_attributes>
      </node>
    </nodes>
    <resources/>
    <constraints/>
  </configuration>
</cib>

.TRY node maintenance node1
.EXT >/dev/null </dev/null crm_shadow 2>&1
.EXT crm_attribute -t nodes -N 'node1' -n maintenance -v 'on'
.EXT >/dev/null </dev/null crm_shadow 2>&1
.INP: configure
.INP: _regtest on
.INP: show xml node1
<?xml version="1.0" ?>
<cib admin_epoch="0" epoch="1" num_updates="1" validate-with="pacemaker-1.2" cib-last-written="Sun Apr 12 21:37:48 2009">
  <configuration>
    <crm_config/>
    <nodes>
      <node uname="node1" id="node1">
        <instance_attributes id="nodes-node1">
          <nvpair id="nodes-node1-standby" name="standby" value="off"/>
          <nvpair id="nodes-node1-maintenance" name="maintenance" value="on"/>
        </instance_attributes>
      </node>
    </nodes>
    <resources/>
    <constraints/>
  </configuration>
</cib>

.TRY node ready node1
.EXT >/dev/null </dev/null crm_shadow 2>&1
.EXT crm_attribute -t nodes -N 'node1' -n maintenance -v 'off'
.EXT >/dev/null </dev/null crm_shadow 2>&1
.INP: configure
.INP: _regtest on
.INP: show xml node1
<?xml version="1.0" ?>
<cib admin_epoch="0" epoch="1" num_updates="1" validate-with="pacemaker-1.2" cib-last-written="Sun Apr 12 21:37:48 2009">
  <configuration>
    <crm_config/>
    <nodes>
      <node uname="node1" id="node1">
        <instance_attributes id="nodes-node1">
          <nvpair id="nodes-node1-standby" name="standby" value="off"/>
          <nvpair id="nodes-node1-maintenance" name="maintenance" value="off"/>
        </instance_attributes>
      </node>
    </nodes>
    <resources/>
    <constraints/>
  </configuration>
</cib>

.TRY node attribute node1 set a1 "1 2 3"
.EXT >/dev/null </dev/null crm_shadow 2>&1
.EXT crm_attribute -t nodes -U 'node1' -n 'a1' -v '1 2 3'
.EXT >/dev/null </dev/null crm_shadow 2>&1
.INP: configure
.INP: _regtest on
.INP: show xml node1
<?xml version="1.0" ?>
<cib admin_epoch="0" epoch="1" num_updates="1" validate-with="pacemaker-1.2" cib-last-written="Sun Apr 12 21:37:48 2009">
  <configuration>
    <crm_config/>
    <nodes>
      <node uname="node1" id="node1">
        <instance_attributes id="nodes-node1">
          <nvpair id="nodes-node1-standby" name="standby" value="off"/>
          <nvpair id="nodes-node1-maintenance" name="maintenance" value="off"/>
          <nvpair id="nodes-node1-a1" name="a1" value="1 2 3"/>
        </instance_attributes>
      </node>
    </nodes>
    <resources/>
    <constraints/>
  </configuration>
</cib>

.TRY node attribute node1 show a1
.EXT >/dev/null </dev/null crm_shadow 2>&1
.EXT crm_attribute -G -t nodes -U 'node1' -n 'a1'
scope=nodes  name=a1 value=1 2 3
.EXT >/dev/null </dev/null crm_shadow 2>&1
.INP: configure
.INP: _regtest on
.INP: show xml node1
<?xml version="1.0" ?>
<cib admin_epoch="0" epoch="1" num_updates="1" validate-with="pacemaker-1.2" cib-last-written="Sun Apr 12 21:37:48 2009">
  <configuration>
    <crm_config/>
    <nodes>
      <node uname="node1" id="node1">
        <instance_attributes id="nodes-node1">
          <nvpair id="nodes-node1-standby" name="standby" value="off"/>
          <nvpair id="nodes-node1-maintenance" name="maintenance" value="off"/>
          <nvpair id="nodes-node1-a1" name="a1" value="1 2 3"/>
        </instance_attributes>
      </node>
    </nodes>
    <resources/>
    <constraints/>
  </configuration>
</cib>

.TRY node attribute node1 delete a1
.EXT >/dev/null </dev/null crm_shadow 2>&1
.EXT crm_attribute -D -t nodes -U 'node1' -n 'a1'
Deleted nodes attribute: id=nodes-node1-a1 name=a1

.EXT >/dev/null </dev/null crm_shadow 2>&1
.INP: configure
.INP: _regtest on
.INP: show xml node1
<?xml version="1.0" ?>
<cib admin_epoch="0" epoch="1" num_updates="1" validate-with="pacemaker-1.2" cib-last-written="Sun Apr 12 21:37:48 2009">
  <configuration>
    <crm_config/>
    <nodes>
      <node uname="node1" id="node1">
        <instance_attributes id="nodes-node1">
          <nvpair id="nodes-node1-standby" name="standby" value="off"/>
          <nvpair id="nodes-node1-maintenance" name="maintenance" value="off"/>
        </instance_attributes>
      </node>
    </nodes>
    <resources/>
    <constraints/>
  </configuration>
</cib>

