.TRY resource status p0
.EXT crm_resource --locate -r 'p0'
resource p0 is NOT running
.SETENV showobj=p3
.TRY resource start p3
.INP: configure
.INP: _regtest on
.INP: show xml p3
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources>
      <primitive id="p3" class="ocf" provider="pacemaker" type="Dummy">
        <meta_attributes id="p3-meta_attributes">
          <nvpair id="p3-meta_attributes-target-role" name="target-role" value="Started"/>
        </meta_attributes>
      </primitive>
    </resources>
    <constraints/>
  </configuration>
</cib>

.TRY resource stop p3
.INP: configure
.INP: _regtest on
.INP: show xml p3
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources>
      <primitive id="p3" class="ocf" provider="pacemaker" type="Dummy">
        <meta_attributes id="p3-meta_attributes">
          <nvpair id="p3-meta_attributes-target-role" name="target-role" value="Stopped"/>
        </meta_attributes>
      </primitive>
    </resources>
    <constraints/>
  </configuration>
</cib>

.SETENV showobj=c1
.TRY resource manage c1
.INP: configure
.INP: _regtest on
.INP: show xml c1
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources>
      <clone id="c1">
        <meta_attributes id="c1-meta_attributes">
          <nvpair id="c1-meta_attributes-is-managed" name="is-managed" value="true"/>
        </meta_attributes>
        <primitive id="p1" class="ocf" provider="pacemaker" type="Dummy"/>
      </clone>
    </resources>
    <constraints/>
  </configuration>
</cib>

.TRY resource unmanage c1
.INP: configure
.INP: _regtest on
.INP: show xml c1
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources>
      <clone id="c1">
        <meta_attributes id="c1-meta_attributes">
          <nvpair id="c1-meta_attributes-is-managed" name="is-managed" value="false"/>
        </meta_attributes>
        <primitive id="p1" class="ocf" provider="pacemaker" type="Dummy"/>
      </clone>
    </resources>
    <constraints/>
  </configuration>
</cib>

.SETENV showobj=cli-prefer-p3
.TRY resource migrate p3 node1
.EXT crm_resource --quiet --move -r 'p3' --node='node1'
.INP: configure
.INP: _regtest on
.INP: show xml cli-prefer-p3
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources/>
    <constraints>
      <rsc_location id="cli-prefer-p3" rsc="p3" role="Started" node="node1" score="INFINITY"/>
    </constraints>
  </configuration>
</cib>

.SETENV showobj=
.TRY resource unmigrate p3
.EXT crm_resource --quiet --clear -r 'p3'
.SETENV showobj=cli-prefer-p3
.TRY resource migrate p3 node1 force
.EXT crm_resource --quiet --move -r 'p3' --node='node1' --force
.INP: configure
.INP: _regtest on
.INP: show xml cli-prefer-p3
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources/>
    <constraints>
      <rsc_location id="cli-prefer-p3" rsc="p3" role="Started" node="node1" score="INFINITY"/>
    </constraints>
  </configuration>
</cib>

.SETENV showobj=
.TRY resource unmigrate p3
.EXT crm_resource --quiet --clear -r 'p3'
.SETENV showobj=p0
.TRY resource param p0 set a0 "1 2 3"
.EXT crm_resource -r 'p0' -p 'a0' -v '1 2 3'

Set 'p0' option: id=p0-instance_attributes-a0 set=p0-instance_attributes name=a0=1 2 3
.INP: configure
.INP: _regtest on
.INP: show xml p0
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources>
      <primitive id="p0" class="ocf" provider="pacemaker" type="Dummy">
        <instance_attributes id="p0-instance_attributes">
          <nvpair id="p0-instance_attributes-a0" name="a0" value="1 2 3"/>
        </instance_attributes>
      </primitive>
    </resources>
    <constraints/>
  </configuration>
</cib>

.TRY resource param p0 show a0
.EXT crm_resource -r 'p0' -g 'a0'
1 2 3
.INP: configure
.INP: _regtest on
.INP: show xml p0
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources>
      <primitive id="p0" class="ocf" provider="pacemaker" type="Dummy">
        <instance_attributes id="p0-instance_attributes">
          <nvpair id="p0-instance_attributes-a0" name="a0" value="1 2 3"/>
        </instance_attributes>
      </primitive>
    </resources>
    <constraints/>
  </configuration>
</cib>

.TRY resource param p0 delete a0
.EXT crm_resource -r 'p0' -d 'a0'
Deleted 'p0' option: id=p0-instance_attributes-a0 name=a0
.INP: configure
.INP: _regtest on
.INP: show xml p0
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources>
      <primitive id="p0" class="ocf" provider="pacemaker" type="Dummy">
        <instance_attributes id="p0-instance_attributes"/>
      </primitive>
    </resources>
    <constraints/>
  </configuration>
</cib>

.TRY resource meta p0 set m0 123
.EXT crm_resource --meta -r 'p0' -p 'm0' -v '123'

Set 'p0' option: id=p0-meta_attributes-m0 set=p0-meta_attributes name=m0=123
.INP: configure
.INP: _regtest on
.INP: show xml p0
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources>
      <primitive id="p0" class="ocf" provider="pacemaker" type="Dummy">
        <instance_attributes id="p0-instance_attributes"/>
        <meta_attributes id="p0-meta_attributes">
          <nvpair id="p0-meta_attributes-m0" name="m0" value="123"/>
        </meta_attributes>
      </primitive>
    </resources>
    <constraints/>
  </configuration>
</cib>

.TRY resource meta p0 show m0
.EXT crm_resource --meta -r 'p0' -g 'm0'
123
.INP: configure
.INP: _regtest on
.INP: show xml p0
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources>
      <primitive id="p0" class="ocf" provider="pacemaker" type="Dummy">
        <instance_attributes id="p0-instance_attributes"/>
        <meta_attributes id="p0-meta_attributes">
          <nvpair id="p0-meta_attributes-m0" name="m0" value="123"/>
        </meta_attributes>
      </primitive>
    </resources>
    <constraints/>
  </configuration>
</cib>

.TRY resource meta p0 delete m0
.EXT crm_resource --meta -r 'p0' -d 'm0'
Deleted 'p0' option: id=p0-meta_attributes-m0 name=m0
.INP: configure
.INP: _regtest on
.INP: show xml p0
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources>
      <primitive id="p0" class="ocf" provider="pacemaker" type="Dummy">
        <instance_attributes id="p0-instance_attributes"/>
        <meta_attributes id="p0-meta_attributes"/>
      </primitive>
    </resources>
    <constraints/>
  </configuration>
</cib>

.TRY resource trace p0 probe
INFO: Trace for p0:monitor is written to /var/lib/heartbeat/trace_ra/
INFO: Trace set, restart p0 to trace non-monitor operations
.INP: configure
.INP: _regtest on
.INP: show xml p0
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources>
      <primitive id="p0" class="ocf" provider="pacemaker" type="Dummy">
        <instance_attributes id="p0-instance_attributes"/>
        <meta_attributes id="p0-meta_attributes"/>
        <operations>
          <op name="monitor" interval="0" id="p0-monitor-0">
            <instance_attributes id="p0-monitor-0-instance_attributes">
              <nvpair name="trace_ra" value="1" id="p0-monitor-0-instance_attributes-trace_ra"/>
            </instance_attributes>
          </op>
        </operations>
      </primitive>
    </resources>
    <constraints/>
  </configuration>
</cib>

.TRY resource trace p0 start
INFO: Trace for p0:start is written to /var/lib/heartbeat/trace_ra/
INFO: Trace set, restart p0 to trace the start operation
.INP: configure
.INP: _regtest on
.INP: show xml p0
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources>
      <primitive id="p0" class="ocf" provider="pacemaker" type="Dummy">
        <instance_attributes id="p0-instance_attributes"/>
        <meta_attributes id="p0-meta_attributes"/>
        <operations>
          <op name="monitor" interval="0" id="p0-monitor-0">
            <instance_attributes id="p0-monitor-0-instance_attributes">
              <nvpair name="trace_ra" value="1" id="p0-monitor-0-instance_attributes-trace_ra"/>
            </instance_attributes>
          </op>
          <op name="start" interval="0" id="p0-start-0">
            <instance_attributes id="p0-start-0-instance_attributes">
              <nvpair name="trace_ra" value="1" id="p0-start-0-instance_attributes-trace_ra"/>
            </instance_attributes>
          </op>
        </operations>
      </primitive>
    </resources>
    <constraints/>
  </configuration>
</cib>

.TRY resource trace p0 stop
INFO: Trace for p0:stop is written to /var/lib/heartbeat/trace_ra/
INFO: Trace set, restart p0 to trace the stop operation
.INP: configure
.INP: _regtest on
.INP: show xml p0
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources>
      <primitive id="p0" class="ocf" provider="pacemaker" type="Dummy">
        <instance_attributes id="p0-instance_attributes"/>
        <meta_attributes id="p0-meta_attributes"/>
        <operations>
          <op name="monitor" interval="0" id="p0-monitor-0">
            <instance_attributes id="p0-monitor-0-instance_attributes">
              <nvpair name="trace_ra" value="1" id="p0-monitor-0-instance_attributes-trace_ra"/>
            </instance_attributes>
          </op>
          <op name="start" interval="0" id="p0-start-0">
            <instance_attributes id="p0-start-0-instance_attributes">
              <nvpair name="trace_ra" value="1" id="p0-start-0-instance_attributes-trace_ra"/>
            </instance_attributes>
          </op>
          <op name="stop" interval="0" id="p0-stop-0">
            <instance_attributes id="p0-stop-0-instance_attributes">
              <nvpair name="trace_ra" value="1" id="p0-stop-0-instance_attributes-trace_ra"/>
            </instance_attributes>
          </op>
        </operations>
      </primitive>
    </resources>
    <constraints/>
  </configuration>
</cib>

.TRY resource untrace p0 probe
.INP: configure
.INP: _regtest on
.INP: show xml p0
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources>
      <primitive id="p0" class="ocf" provider="pacemaker" type="Dummy">
        <instance_attributes id="p0-instance_attributes"/>
        <meta_attributes id="p0-meta_attributes"/>
        <operations>
          <op name="start" interval="0" id="p0-start-0">
            <instance_attributes id="p0-start-0-instance_attributes">
              <nvpair name="trace_ra" value="1" id="p0-start-0-instance_attributes-trace_ra"/>
            </instance_attributes>
          </op>
          <op name="stop" interval="0" id="p0-stop-0">
            <instance_attributes id="p0-stop-0-instance_attributes">
              <nvpair name="trace_ra" value="1" id="p0-stop-0-instance_attributes-trace_ra"/>
            </instance_attributes>
          </op>
        </operations>
      </primitive>
    </resources>
    <constraints/>
  </configuration>
</cib>

.TRY resource untrace p0 start
.INP: configure
.INP: _regtest on
.INP: show xml p0
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources>
      <primitive id="p0" class="ocf" provider="pacemaker" type="Dummy">
        <instance_attributes id="p0-instance_attributes"/>
        <meta_attributes id="p0-meta_attributes"/>
        <operations>
          <op name="stop" interval="0" id="p0-stop-0">
            <instance_attributes id="p0-stop-0-instance_attributes">
              <nvpair name="trace_ra" value="1" id="p0-stop-0-instance_attributes-trace_ra"/>
            </instance_attributes>
          </op>
        </operations>
      </primitive>
    </resources>
    <constraints/>
  </configuration>
</cib>

.TRY resource untrace p0 stop
.INP: configure
.INP: _regtest on
.INP: show xml p0
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources>
      <primitive id="p0" class="ocf" provider="pacemaker" type="Dummy">
        <instance_attributes id="p0-instance_attributes"/>
        <meta_attributes id="p0-meta_attributes"/>
      </primitive>
    </resources>
    <constraints/>
  </configuration>
</cib>

.TRY configure group g p0 p3
.INP: configure
.INP: _regtest on
.INP: show xml p0
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources>
      <group id="g">
        <primitive id="p0" class="ocf" provider="pacemaker" type="Dummy">
          <instance_attributes id="p0-instance_attributes"/>
          <meta_attributes id="p0-meta_attributes"/>
        </primitive>
        <primitive id="p3" class="ocf" provider="pacemaker" type="Dummy">
          <meta_attributes id="p3-meta_attributes">
            <nvpair id="p3-meta_attributes-target-role" name="target-role" value="Stopped"/>
          </meta_attributes>
        </primitive>
      </group>
    </resources>
    <constraints/>
  </configuration>
</cib>

.TRY options manage-children never
.INP: configure
.INP: _regtest on
.INP: show xml p0
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources>
      <group id="g">
        <primitive id="p0" class="ocf" provider="pacemaker" type="Dummy">
          <instance_attributes id="p0-instance_attributes"/>
          <meta_attributes id="p0-meta_attributes"/>
        </primitive>
        <primitive id="p3" class="ocf" provider="pacemaker" type="Dummy">
          <meta_attributes id="p3-meta_attributes">
            <nvpair id="p3-meta_attributes-target-role" name="target-role" value="Stopped"/>
          </meta_attributes>
        </primitive>
      </group>
    </resources>
    <constraints/>
  </configuration>
</cib>

.TRY resource start g
.INP: configure
.INP: _regtest on
.INP: show xml p0
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources>
      <group id="g">
        <meta_attributes id="g-meta_attributes">
          <nvpair id="g-meta_attributes-target-role" name="target-role" value="Started"/>
        </meta_attributes>
        <primitive id="p0" class="ocf" provider="pacemaker" type="Dummy"/>
        <primitive id="p3" class="ocf" provider="pacemaker" type="Dummy">
          <meta_attributes id="p3-meta_attributes">
            <nvpair id="p3-meta_attributes-target-role" name="target-role" value="Stopped"/>
          </meta_attributes>
        </primitive>
      </group>
    </resources>
    <constraints/>
  </configuration>
</cib>

.TRY resource start p0
.INP: configure
.INP: _regtest on
.INP: show xml p0
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources>
      <group id="g">
        <meta_attributes id="g-meta_attributes">
          <nvpair id="g-meta_attributes-target-role" name="target-role" value="Started"/>
        </meta_attributes>
        <primitive id="p0" class="ocf" provider="pacemaker" type="Dummy">
          <meta_attributes id="p0-meta_attributes">
            <nvpair id="p0-meta_attributes-target-role" name="target-role" value="Started"/>
          </meta_attributes>
        </primitive>
        <primitive id="p3" class="ocf" provider="pacemaker" type="Dummy">
          <meta_attributes id="p3-meta_attributes">
            <nvpair id="p3-meta_attributes-target-role" name="target-role" value="Stopped"/>
          </meta_attributes>
        </primitive>
      </group>
    </resources>
    <constraints/>
  </configuration>
</cib>

.TRY resource stop g
.INP: configure
.INP: _regtest on
.INP: show xml p0
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources>
      <group id="g">
        <meta_attributes id="g-meta_attributes">
          <nvpair id="g-meta_attributes-target-role" name="target-role" value="Stopped"/>
        </meta_attributes>
        <primitive id="p0" class="ocf" provider="pacemaker" type="Dummy">
          <meta_attributes id="p0-meta_attributes">
            <nvpair id="p0-meta_attributes-target-role" name="target-role" value="Started"/>
          </meta_attributes>
        </primitive>
        <primitive id="p3" class="ocf" provider="pacemaker" type="Dummy">
          <meta_attributes id="p3-meta_attributes">
            <nvpair id="p3-meta_attributes-target-role" name="target-role" value="Stopped"/>
          </meta_attributes>
        </primitive>
      </group>
    </resources>
    <constraints/>
  </configuration>
</cib>

.TRY configure clone cg g
.INP: configure
.INP: _regtest on
.INP: show xml p0
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources>
      <clone id="cg">
        <group id="g">
          <meta_attributes id="g-meta_attributes">
            <nvpair id="g-meta_attributes-target-role" name="target-role" value="Stopped"/>
          </meta_attributes>
          <primitive id="p0" class="ocf" provider="pacemaker" type="Dummy">
            <meta_attributes id="p0-meta_attributes">
              <nvpair id="p0-meta_attributes-target-role" name="target-role" value="Started"/>
            </meta_attributes>
          </primitive>
          <primitive id="p3" class="ocf" provider="pacemaker" type="Dummy">
            <meta_attributes id="p3-meta_attributes">
              <nvpair id="p3-meta_attributes-target-role" name="target-role" value="Stopped"/>
            </meta_attributes>
          </primitive>
        </group>
      </clone>
    </resources>
    <constraints/>
  </configuration>
</cib>

.TRY options manage-children always
.INP: configure
.INP: _regtest on
.INP: show xml p0
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources>
      <clone id="cg">
        <group id="g">
          <meta_attributes id="g-meta_attributes">
            <nvpair id="g-meta_attributes-target-role" name="target-role" value="Stopped"/>
          </meta_attributes>
          <primitive id="p0" class="ocf" provider="pacemaker" type="Dummy">
            <meta_attributes id="p0-meta_attributes">
              <nvpair id="p0-meta_attributes-target-role" name="target-role" value="Started"/>
            </meta_attributes>
          </primitive>
          <primitive id="p3" class="ocf" provider="pacemaker" type="Dummy">
            <meta_attributes id="p3-meta_attributes">
              <nvpair id="p3-meta_attributes-target-role" name="target-role" value="Stopped"/>
            </meta_attributes>
          </primitive>
        </group>
      </clone>
    </resources>
    <constraints/>
  </configuration>
</cib>

.TRY resource start g
.INP: configure
.INP: _regtest on
.INP: show xml p0
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources>
      <clone id="cg">
        <meta_attributes id="cg-meta_attributes">
          <nvpair id="cg-meta_attributes-target-role" name="target-role" value="Started"/>
        </meta_attributes>
        <group id="g">
          <primitive id="p0" class="ocf" provider="pacemaker" type="Dummy">
            <meta_attributes id="p0-meta_attributes">
              <nvpair id="p0-meta_attributes-target-role" name="target-role" value="Started"/>
            </meta_attributes>
          </primitive>
          <primitive id="p3" class="ocf" provider="pacemaker" type="Dummy"/>
        </group>
      </clone>
    </resources>
    <constraints/>
  </configuration>
</cib>

.TRY resource stop g
.INP: configure
.INP: _regtest on
.INP: show xml p0
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources>
      <clone id="cg">
        <meta_attributes id="cg-meta_attributes">
          <nvpair id="cg-meta_attributes-target-role" name="target-role" value="Stopped"/>
        </meta_attributes>
        <group id="g">
          <primitive id="p0" class="ocf" provider="pacemaker" type="Dummy"/>
          <primitive id="p3" class="ocf" provider="pacemaker" type="Dummy"/>
        </group>
      </clone>
    </resources>
    <constraints/>
  </configuration>
</cib>

.TRY resource start cg
.INP: configure
.INP: _regtest on
.INP: show xml p0
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources>
      <clone id="cg">
        <meta_attributes id="cg-meta_attributes">
          <nvpair id="cg-meta_attributes-target-role" name="target-role" value="Started"/>
        </meta_attributes>
        <group id="g">
          <primitive id="p0" class="ocf" provider="pacemaker" type="Dummy"/>
          <primitive id="p3" class="ocf" provider="pacemaker" type="Dummy"/>
        </group>
      </clone>
    </resources>
    <constraints/>
  </configuration>
</cib>

.TRY resource stop p0
.INP: configure
.INP: _regtest on
.INP: show xml p0
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources>
      <clone id="cg">
        <meta_attributes id="cg-meta_attributes">
          <nvpair id="cg-meta_attributes-target-role" name="target-role" value="Started"/>
        </meta_attributes>
        <group id="g">
          <primitive id="p0" class="ocf" provider="pacemaker" type="Dummy">
            <meta_attributes id="p0-meta_attributes">
              <nvpair id="p0-meta_attributes-target-role" name="target-role" value="Stopped"/>
            </meta_attributes>
          </primitive>
          <primitive id="p3" class="ocf" provider="pacemaker" type="Dummy"/>
        </group>
      </clone>
    </resources>
    <constraints/>
  </configuration>
</cib>

.TRY resource start cg
.INP: configure
.INP: _regtest on
.INP: show xml p0
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources>
      <clone id="cg">
        <meta_attributes id="cg-meta_attributes">
          <nvpair id="cg-meta_attributes-target-role" name="target-role" value="Started"/>
        </meta_attributes>
        <group id="g">
          <primitive id="p0" class="ocf" provider="pacemaker" type="Dummy"/>
          <primitive id="p3" class="ocf" provider="pacemaker" type="Dummy"/>
        </group>
      </clone>
    </resources>
    <constraints/>
  </configuration>
</cib>

.TRY resource stop cg
.INP: configure
.INP: _regtest on
.INP: show xml p0
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources>
      <clone id="cg">
        <meta_attributes id="cg-meta_attributes">
          <nvpair id="cg-meta_attributes-target-role" name="target-role" value="Stopped"/>
        </meta_attributes>
        <group id="g">
          <primitive id="p0" class="ocf" provider="pacemaker" type="Dummy"/>
          <primitive id="p3" class="ocf" provider="pacemaker" type="Dummy"/>
        </group>
      </clone>
    </resources>
    <constraints/>
  </configuration>
</cib>

.TRY resource stop p3
.INP: configure
.INP: _regtest on
.INP: show xml p0
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources>
      <clone id="cg">
        <meta_attributes id="cg-meta_attributes">
          <nvpair id="cg-meta_attributes-target-role" name="target-role" value="Stopped"/>
        </meta_attributes>
        <group id="g">
          <primitive id="p0" class="ocf" provider="pacemaker" type="Dummy"/>
          <primitive id="p3" class="ocf" provider="pacemaker" type="Dummy">
            <meta_attributes id="p3-meta_attributes">
              <nvpair id="p3-meta_attributes-target-role" name="target-role" value="Stopped"/>
            </meta_attributes>
          </primitive>
        </group>
      </clone>
    </resources>
    <constraints/>
  </configuration>
</cib>

.TRY configure rename p3 p4
.EXT crm_resource --show-metadata ocf:pacemaker:Dummy
.EXT crm_resource --show-metadata ocf:heartbeat:Delay
.EXT crm_resource --show-metadata stonith:null
.EXT stonithd metadata
.INP: configure
.INP: _regtest on
.INP: show xml p0
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources>
      <clone id="cg">
        <meta_attributes id="cg-meta_attributes">
          <nvpair id="cg-meta_attributes-target-role" name="target-role" value="Stopped"/>
        </meta_attributes>
        <group id="g">
          <primitive id="p0" class="ocf" provider="pacemaker" type="Dummy"/>
          <primitive id="p4" class="ocf" provider="pacemaker" type="Dummy">
            <meta_attributes id="p3-meta_attributes">
              <nvpair id="p3-meta_attributes-target-role" name="target-role" value="Stopped"/>
            </meta_attributes>
          </primitive>
        </group>
      </clone>
    </resources>
    <constraints/>
  </configuration>
</cib>

.TRY configure primitive p3 Dummy
.EXT crm_resource --show-metadata ocf:pacemaker:Dummy
.EXT crm_resource --show-metadata ocf:heartbeat:Delay
.EXT crm_resource --show-metadata stonith:null
.EXT stonithd metadata
.EXT crm_resource --show-metadata ocf:heartbeat:Dummy
.INP: configure
.INP: _regtest on
.INP: show xml p0
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources>
      <clone id="cg">
        <meta_attributes id="cg-meta_attributes">
          <nvpair id="cg-meta_attributes-target-role" name="target-role" value="Stopped"/>
        </meta_attributes>
        <group id="g">
          <primitive id="p0" class="ocf" provider="pacemaker" type="Dummy"/>
          <primitive id="p4" class="ocf" provider="pacemaker" type="Dummy">
            <meta_attributes id="p3-meta_attributes">
              <nvpair id="p3-meta_attributes-target-role" name="target-role" value="Stopped"/>
            </meta_attributes>
          </primitive>
        </group>
      </clone>
    </resources>
    <constraints/>
  </configuration>
</cib>

.TRY resource stop p3
.INP: configure
.INP: _regtest on
.INP: show xml p0
<?xml version="1.0" ?>
<cib>
  <configuration>
    <crm_config/>
    <nodes/>
    <resources>
      <clone id="cg">
        <meta_attributes id="cg-meta_attributes">
          <nvpair id="cg-meta_attributes-target-role" name="target-role" value="Stopped"/>
        </meta_attributes>
        <group id="g">
          <primitive id="p0" class="ocf" provider="pacemaker" type="Dummy"/>
          <primitive id="p4" class="ocf" provider="pacemaker" type="Dummy">
            <meta_attributes id="p3-meta_attributes">
              <nvpair id="p3-meta_attributes-target-role" name="target-role" value="Stopped"/>
            </meta_attributes>
          </primitive>
        </group>
      </clone>
    </resources>
    <constraints/>
  </configuration>
</cib>

