.TRY Resource sets
.INP: configure
.INP: _regtest on
.INP: erase
.INP: erase nodes
.INP: node node1
.INP: primitive st stonith:ssh 	params hostlist='node1'
.INP: primitive d1 ocf:pacemaker:Dummy
.INP: primitive d2 ocf:heartbeat:Dummy
.INP: primitive d3 ocf:heartbeat:Dummy
.INP: primitive d4 ocf:heartbeat:Dummy
.INP: primitive d5 ocf:heartbeat:Dummy
.INP: order o1 inf: d1 d2 ( d3 d4 )
.INP: colocation c1 inf: d4 ( d1 d2 d3 )
.INP: colocation c2 inf: d1 d2 d3 d4
.INP: colocation c3 inf: ( d3 d4 ) ( d1 d2 )
.INP: delete d2
INFO: 16: constraint order:o1 updated
INFO: 16: constraint colocation:c1 updated
INFO: 16: constraint colocation:c2 updated
INFO: 16: constraint colocation:c3 updated
.INP: show o1 c1 c2 c3
colocation c1 inf: d4 ( d1 d3 )
colocation c2 inf: d1 d3 d4
colocation c3 inf: ( d3 d4 ) ( d1 )
order o1 inf: d1 ( d3 d4 )
.INP: delete d4
INFO: 18: constraint order:o1 updated
INFO: 18: constraint colocation:c1 updated
INFO: 18: constraint colocation:c2 updated
INFO: 18: constraint colocation:c3 updated
.INP: show o1 c1 c2 c3
colocation c1 inf: ( d1 d3 )
colocation c2 inf: d3 d1
colocation c3 inf: d3 d1
order o1 inf: d1 d3
.INP: show xml o1 c1 c2 c3
<?xml version="1.0" ?>
<cib admin_epoch="0" crm_feature_set="3.0.1" dc-uuid="f36760d8-d84a-46b2-b452-4c8cac8b3396" epoch="0" have-quorum="1" num_updates="1" remote-tls-port="0" validate-with="pacemaker-1.1">
  <configuration>
    <crm_config/>
    <nodes/>
    <resources/>
    <constraints>
      <rsc_order first="d1" id="o1" score="INFINITY" then="d3"/>
      <rsc_colocation id="c1" score="INFINITY">
        <resource_set id="c1-1" sequential="false">
          <resource_ref id="d1"/>
          <resource_ref id="d3"/>
        </resource_set>
      </rsc_colocation>
      <rsc_colocation id="c2" rsc="d3" score="INFINITY" with-rsc="d1"/>
      <rsc_colocation id="c3" rsc="d3" score="INFINITY" with-rsc="d1"/>
    </constraints>
  </configuration>
</cib>

.INP: _test
.INP: verify
.INP: show
node node1
primitive d1 ocf:pacemaker:Dummy
primitive d3 ocf:heartbeat:Dummy
primitive d5 ocf:heartbeat:Dummy
primitive st stonith:ssh \
	params hostlist="node1"
colocation c1 inf: ( d1 d3 )
colocation c2 inf: d3 d1
colocation c3 inf: d3 d1
order o1 inf: d1 d3
.INP: commit
