---

- name: "{{ name }}.check"
  shell: |
    DEF_WDTIMEOUT={{ expected[name] }}
    result_wdtimeout=${DEF_WDTIMEOUT}
    sbdarray=$(grep -E '^SBD_DEVICE=' /etc/sysconfig/sbd  | grep -oP 'SBD_DEVICE=\K[^.]+' | sed 's/\"//g')
    IFS=';' sbdarray=( $sbdarray )
    for i in "${sbdarray[@]}"
    do
      wdtimeout=$(/usr/sbin/sbd -d ${i} dump | grep -oP 'Timeout \(watchdog\)  *: \K\d+')|| echo ""
      if [[ "${wdtimeout}" -ne "${DEF_WDTIMEOUT}" ]]; then
        result_wdtimeout="${wdtimeout}"
      fi
    done
    echo "${result_wdtimeout}"
  check_mode: false
  register: config_updated
  changed_when: config_updated.stdout != expected[name]

- block:
    - name: Post results
      import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is not changed }}"
