- hosts: all
  gather_facts: false
  ignore_errors: true
  become: true
  timeout: 30  # Task timeout set to 30 seconds. If some task needs a bigger timeout, set a new timeout in the task itself

  vars:
    crmsh_labels:
      - test  # Do not change the name. It is use in the crmsh_callback call

  tasks:
    - name: require check mode
      fail:
        msg: "Only supported for --check option"
      when:
        - not ansible_check_mode

    - name: Include load_facts
      import_role:
        name: load_facts

    - name: Find checks
      find:
        paths: "{{ playbook_dir }}/roles/checks"
        file_type: directory
      register: checks
      run_once: true
      delegate_to: localhost

    # Do not change the name. It is use in the crmsh_callback call
    - name: run_checks
      include_role:
        name: "{{ check_item.path }}"
      loop: "{{ checks.files|sort(attribute='path') }}"
      loop_control:
        loop_var: check_item  # Do not change the name. It is use in the crmsh_callback call
      when: ((lookup("file", check_item.path+"/defaults/main.yml")|from_yaml).id|string)|default("") in cluster_selected_checks_list
      #when: (check_item.path | basename) in cluster_selected_checks_list
