---

name: 1.1.2
group: Corosync
labels: generic
description: |
  Corosync `consensus` timeout is set to `{{ expected[name] }}`
remediation: |
  ## Remediation
  Adjust the Corosync `consensus` timeout as recommended by the Azure best practices.

  ## References
  - https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker
implementation: "{{ lookup('file', 'roles/checks/'+name+'/tasks/main.yml') }}"

# Test data
key_name: consensus

# check id. This value must not be changed over the life of this check
id: A1244C
