= Documentation =

`crmsh` begun as a bundled interface to the Pacemaker cluster manager,
but has grown beyond simply configuring Pacemaker to handling many
more aspects of the Linux HA stack. It also serves as the backend for
the Hawk web interface.

The main documentation for `crmsh` comes in the form of the 
_manual_, which is the same help as found using the `help`
command in the interactive shell.

Beyond this, we've also written a couple of guides and other documents
that will hopefully make using the shell as simple and painless as
possible.

== Documents ==

* link:/man[Manual (Development)], link:/man-2.0[(Release 2.x)], link:/man-1.2[(Release 1.2)]
* link:/installation[Installation]
* link:/start-guide[Getting Started]
* link:/history-guide[History Guide]
* link:/rsctest-guide[Resource Testing Guide]
* link:/configuration[Configuration]
* link:/scripts[Cluster scripts]
* link:/faq[Frequently Asked Questions]

== Translations ==

* https://blog.3ware.co.jp/2015/05/crmsh-getting-started/[Getting Started (Japanese)]

== External documentation ==

The SUSE
https://www.suse.com/documentation/sle_ha/book_sleha/?page=/documentation/sle_ha/book_sleha/data/book_sleha.html[High
Availability Guide] provides a guide to
installing and configuring a complete cluster solution including both
the `crm` shell and Hawk, the web GUI which uses the `crm` shell as
its backend.

For more information on Pacemaker in general, see the
http://clusterlabs.org/doc/[Pacemaker documentation] at `clusterlabs.org`.

For details on command line usage, see the link:/man[Manual].

