= Documentation =

The main documentation for `crmsh` comes in the form of the 
`manual`, which is the same help as found using the `help`
command in the interactive shell.

Additionally, there are a couple of guides and other documents
that will hopefully make using the shell as easy as possible.

== Manual ==

* link:/man[Manual (Development)]
* link:/man-4.6[Manual (v4.6.x)]
* link:/man-4.3[Manual (v4.3.x)]
* link:/man-3[Manual (v3.x)]
* link:/man-2.0[Manual (v2.x)]
* link:/man-1.2[Manual (v1.2.x)]

== Guides ==

* link:/start-guide[Getting Started]
* link:/history-guide[History Guide]
* link:/rsctest-guide[Resource Testing Guide]
* link:/configuration[Configuration]
* link:/scripts[Cluster scripts]
* link:/faq[Frequently Asked Questions]

== Translations ==

* https://blog.3ware.co.jp/2015/05/crmsh-getting-started/[Getting Started (Japanese)]

== External documentation ==

The SUSE
https://www.suse.com/documentation/sle_ha/book_sleha/?page=/documentation/sle_ha/book_sleha/data/book_sleha.html[High
Availability Guide] provides a guide to
installing and configuring a complete cluster solution including both
the `crm` shell and Hawk, the web GUI which uses the `crm` shell as
its backend.

For more information on Pacemaker in general, see the
http://clusterlabs.org/doc/[Pacemaker documentation] at `clusterlabs.org`.

