#!/usr/bin/python3
import os
import sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from preflight_check import main


if __name__ == "__main__":
    main.ctx.process_name = os.path.basename(sys.argv[0])
    main.run(main.ctx)
