---

name: 2.2.4
group: OS and package versions
labels: hana
description: |
  Corosync version is supported
remediation: |
  ## Abstract
  Installed Corosync version must be equal or higher than {{ expected['2.2.4'] }}

  ## Remediation
  Install or upgrade to a supported Corosync version

  ## Reference
  - https://documentation.suse.com/en-us/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/
implementation: "{{ lookup('file', 'roles/checks/'+name+'/tasks/main.yml') }}"

# check id. This value must not be changed over the life of this check
id: DC5429
